/**
 * Every permission the API knows (Educa_Lara app/Domain/Access/PermissionRegistry.php).
 * Typed, so a misspelt permission in a guard or nav item is a compile error.
 * Keep in step with the registry; the API remains the authority on what is allowed.
 */
export const PERMISSIONS = [
  'access_admin_app',
  'access_staff_portal',
  'view_dashboard',
  'view_exam_analysis',
  'manage_school_profile',
  'manage_academic_calendar',
  'manage_classes',
  'manage_subjects',
  'manage_grading_scales',
  'create_exams',
  'update_exams',
  'delete_exams',
  'change_exam_status',
  'compute_exam_results',
  'view_marksheets',
  'enter_marks',
  'set_max_marks',
  'mark_any_class',
  'view_marklists',
  'view_report_cards',
  'edit_report_entries',
  'access_any_class',
  'view_students',
  'create_students',
  'update_students',
  'move_students',
  'change_student_status',
  'delete_students',
  'promote_students',
  'view_class_pupils',
  'admit_class_pupils',
  'move_class_pupils',
  'view_staff',
  'create_staff',
  'update_staff',
  'delete_staff',
  'invite_staff',
  'reset_staff_passwords',
  'sign_out_staff',
  'manage_assignments',
  'manage_billing',
  'view_roles',
  'manage_roles',
  'manage_schools',
  'view_system_health',
  'manage_subscriptions',
] as const

export type Permission = (typeof PERMISSIONS)[number]
